# Generated by Django 5.1.3 on 2024-11-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('cnaps', models.CharField(max_length=20)),
                ('commune', models.CharField(max_length=100)),
                ('nom_banque', models.CharField(max_length=100)),
                ('cle', models.CharField(max_length=10)),
                ('code_postal', models.CharField(max_length=10)),
            ],
        ),
    ]
