# Generated by Django 5.1.3 on 2024-11-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_log', '0002_alter_information_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='num_bancaire',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
