# Generated by Django 5.1.3 on 2024-11-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_log', '0003_information_num_bancaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_urgence', models.CharField(max_length=300)),
                ('etat_sante', models.CharField(max_length=200)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_log.information')),
            ],
        ),
    ]
