# Generated by Django 5.1.3 on 2024-11-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_log', '0004_sante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sante',
            name='etat_sante',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sante',
            name='tel_urgence',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
