# Generated by Django 5.1.3 on 2024-11-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_log', '0005_alter_sante_etat_sante_alter_sante_tel_urgence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_anterieur', models.CharField(max_length=200)),
                ('periode_debut', models.CharField(max_length=100)),
                ('periode_fin', models.CharField(max_length=100)),
                ('adresse_employeur', models.CharField(max_length=200)),
                ('poste_contrat', models.CharField(max_length=100)),
                ('type_contrat', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=100)),
                ('horaire_hebdo', models.CharField(max_length=10)),
                ('debut_contrat', models.CharField(max_length=20)),
                ('fin_contrat', models.CharField(max_length=10)),
                ('salaire_net', models.CharField(max_length=20)),
                ('salaire_brut', models.CharField(max_length=20)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_log.information')),
            ],
        ),
    ]
